### ISSUE TITLE
About text

### ISSUE THREAD

**Issue by olafveerman** [developmentseed/worldpop#28]
I assume the 'About WorldPop' description is about the data source? Currently it reads like a description of the tool itself.

**Comment by anandthakker** [comment]
Yes - that text is lifted straight from http://www.worldpop.org.uk/, and should maybe be relabeled "About the Data"?

**Comment by anandthakker** [comment]
Made the above change; closing for now.  Later we'll need more substantive look at the text content, but that'll be a separate ticket.
