### ISSUE TITLE
Design baselayer

### ISSUE THREAD

**Issue by olafveerman** [developmentseed/worldpop#30]
The design of the current baselayer is busy, especially with a lot of streets:

![image](https://cloud.githubusercontent.com/assets/751330/7343904/e8b363dc-ecbe-11e4-8b00-54d7fe77151d.png)

and rivers:

![image](https://cloud.githubusercontent.com/assets/751330/7343928/1d16f760-ecbf-11e4-80e4-0e02ee47faaa.png)

Also, the **labels** could be more clear. Darker font and maybe less opacity on the halo?

**Comment by anandthakker** [comment]
Agreed, this definitely needs work.

It's currently just our data layer with a (lightly modified) Mapbox Light plopped on top of it... I've never built up a baselayer from scratch before, but possibly that would be a better/cleaner approach?

**Comment by anandthakker** [comment]
Added the Mapbox Studio project as a separate repo: https://github.com/developmentseed/worldpop-basemap.tm2

**Comment by anandthakker** [comment]
See developmentseed/worldpop-basemap.tm2#1

**Comment by anandthakker** [comment]
@DylanMoriarty did this!
