### ISSUE TITLE
Adding multipolygon geojson causes loader to wig out

### ISSUE THREAD

**Issue by DylanMoriarty** [developmentseed/worldpop#52]
Dropping a geojson with multiple polygons seems to cause some issues at the moment. I'm adding two quick geojsons I put together which cause consistent errors when added.

**3-Polygon geojson**
https://drive.google.com/a/developmentseed.org/file/d/0B4gmhcCVsfP4YnNqWUNwa19EVEU/view?usp=sharing

Dragging this one in causes the app to wig out.
![loading dance](http://i.imgur.com/1B5Vpxe.gif)

**5-Polygon geojson**
https://drive.google.com/a/developmentseed.org/file/d/0B4gmhcCVsfP4Rl9leS1RbHo0NGs/view?usp=sharing

Dragging this one in causes it to initially act like the first geojson, but then it settles on just displaying one of the five polygons.

**Comment by DylanMoriarty** [comment]
Turns out just reloading the page when there's multiple polygons drawn on it causes a similar wig out, so it's probably how the code is processing multiple areas rather than something with the geojson processing.

**Comment by anandthakker** [comment]
Good call @DylanMoriarty
